{
  "formatVersion": "1.1",
  "component": {
    "group": "io.openweb3",
    "module": "bridge",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "bridge-1.0.7.aar",
          "url": "bridge-1.0.7.aar",
          "size": 2601,
          "sha512": "dfe9d064f05fce2e5420b268a6696fdbc273ffda972983554543e46a9fd6a5897f3bc3f8b37289876a65f7bfe715e8f95d2d8fef40033a774be08aeed768b14f",
          "sha256": "68ca7e7e8db36e7da168e62c7e1f87f69f62d5eddc7e69d5db2cb2c4b02ab8e7",
          "sha1": "e7a1c1704b91c5c5ef6fd0fdeb6599b9992c9254",
          "md5": "e116857c79a76b593d3a4b07d8a5933d"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "bridge-1.0.7.aar",
          "url": "bridge-1.0.7.aar",
          "size": 2601,
          "sha512": "dfe9d064f05fce2e5420b268a6696fdbc273ffda972983554543e46a9fd6a5897f3bc3f8b37289876a65f7bfe715e8f95d2d8fef40033a774be08aeed768b14f",
          "sha256": "68ca7e7e8db36e7da168e62c7e1f87f69f62d5eddc7e69d5db2cb2c4b02ab8e7",
          "sha1": "e7a1c1704b91c5c5ef6fd0fdeb6599b9992c9254",
          "md5": "e116857c79a76b593d3a4b07d8a5933d"
        }
      ]
    }
  ]
}
